// Property data
const properties = [
  {
    id: 22,
    name: "Riviera Maya",
    new: "",
    address: "116 S. Franklin Road",
    city: "Bloomington",
    state: "IN",
    zip: "47404",
    info: "",
    imageUrl: "./assets/propertyimage/rivieramaya.jpg",
    webPage: "./properties/116-S-Franklin.html",
    lat: 39.16741,
    lng: -86.57157,
  },
  {
    id: 57,
    name: "118-124 E. Kirkwood",
    new: "",
    address: "118-124 East Kirkwood Avenue",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./assets/propertyimage/kirkwood.jpg",
    webPage: "./properties/118-124-Kirkwood.html",
    lat: 39.16635,
    lng: -86.53277,
  },
  {
    id: 32,
    name: "Academy Sports + Outdoors",
    new: "",
    address: "123 S. Kingston Drive",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./assets/propertyimage/academy2.jpg",
    webPage: "./properties/123-S-Kingston.html",
    lat: 39.16612,
    lng: -86.49220,
  },
  {
    id: 21,
    name: "Pizza Hut",
    new: "",
    address: "125 S. Franklin Road",
    city: "Bloomington",
    state: "IN",
    zip: "47404",
    info: "",
    imageUrl: "./assets/propertyimage/pizzahut.jpg",
    webPage: "./properties/125-S-Franklin.html",
    lat: 39.16587,
    lng: -86.57067,
  },
  {
    id: 40,
    name: "Kingston Shoppes",
    new: "",
    address: "143-167 S. Kingston Drive",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./assets/propertyimage/kingston_shoppes.jpg",
    webPage: "./properties/kingston-shoppes.html",
    lat: 39.16601,
    lng: -86.49118,
  },
  {
    id: 2,
    name: "Chow Bar + Toppers Pizza",
    new: "",
    address: "212 S. Indiana Avenue",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./assets/propertyimage/toppers.jpg",
    webPage: "./properties/212-S-Indiana.html",
    lat: 39.16490,
    lng: -86.52706,
  },
  {
    id: 16,
    name: "Friendly & Fresh",
    new: "",
    address: "275 E. Winslow Road",
    city: "Bloomington",
    state: "IN",
    zip: "47401",
    info: "",
    imageUrl: "./assets/propertyimage/rajeshstation.jpg",
    webPage: "./properties/275-E-Winslow.html",
    lat: 39.13643,
    lng: -86.52726,
  },
  {
    id: 9,
    name: "Korea Restaurant",
    new: "",
    address: "409 E. 4th Street",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./assets/propertyimage/korearestaurant.jpg",
    webPage: "./properties/409-E-4th.html",
    lat: 39.16575,
    lng: -86.52928,
  },
  {
    id: 8,
    name: "Burma Garden Restaurant",
    new: "",
    address: "413 E. 4th Street",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./assets/propertyimage/burmagarden.jpg",
    webPage: "./properties/413-E-4th.html",
    lat: 39.16572,
    lng: -86.52910,
  },
  {
    id: 11,
    name: "India Garden",
    new: "",
    address: "416 E. 4th Street",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./assets/propertyimage/indiagarden.jpg",
    webPage: "./properties/416-E-4th.html",
    lat: 39.16545,
    lng: -86.52869,
  },
  {
    id: 33,
    name: "Dunnkirk Square",
    new: "",
    address: "430 E. Kirkwood Avenue",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./assets/propertyimage/dunnkirk_square.jpg",
    webPage: "./properties/dunkirk-square.html",
    lat: 39.16628,
    lng: -86.52853,
  },
  {
    id: 26,
    name: "Smokin' Jack's Rib Shack",
    new: "",
    address: "505 W. 17th Street",
    city: "Bloomington",
    state: "IN",
    zip: "47404",
    info: "",
    imageUrl: "./assets/propertyimage/smokinjacks.jpg",
    webPage: "./properties/505-W-17th.html",
    lat: 39.17872,
    lng: -86.53865,
  },
  {
    id: 55,
    name: "Circle K",
    new: "",
    address: "545 S. Rangeline Road",
    city: "Carmel",
    state: "IN",
    zip: "46032",
    info: "",
    imageUrl: "./assets/propertyimage/carmel.jpg",
    webPage: "./properties/545-S-Rangeline.html",
    lat: 39.9733,
    lng: -86.12653,
  },
  {
    id: 17,
    name: "Grab & Go",
    new: "",
    address: "901 N. Indiana Avenue",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./assets/propertyimage/grabngo.jpg",
    webPage: "./properties/901-N-Indiana.html",
    lat: 39.17478,
    lng: -86.52730,
  },
/*   {
    id: 54,
    name: "Phillips 66",
    new: "",
    address: "910 3rd Street",
    city: "Columbus",
    state: "IN",
    zip: "47201",
    info: "",
    imageUrl: "./assets/propertyimage/phillips.jpg",
    webPage: "./properties/construction.html",
    lat: 39.20190,
    lng: -85.91406,
  }, */
  {
    id: 18,
    name: "Village Pantry",
    new: "",
    address: "1320 E. 3rd Street",
    city: "Bloomington",
    state: "IN",
    zip: "47401",
    info: "",
    imageUrl: "./assets/propertyimage/villagepantry.jpg",
    webPage: "./properties/1320-E-3rd.html",
    lat: 39.16408,
    lng: -86.51669,
  },
  // {
  //   id: 55,
  //   name: "Sunset Hill Fence + Performance Refinish Supply",
  //   new: "",
  //   address: "1400 - 1440 W. Bloomfield Rd.",
  //   city: "Bloomington",
  //   state: "IN",
  //   zip: "47401",
  //   info: "",
  //   imageUrl: "./assets/propertyimage/sunsethillfence.jpg",
  //   webPage: "./properties/construction.html",
  //   lat: 39.15971,
  //   lng: -86.55564,
  // },
  {
    id: 28,
    name: "K&K Sales",
    new: "",
    address: "1440 S. Liberty",
    city: "Bloomington",
    state: "IN",
    zip: "47403",
    info: "",
    imageUrl: "./assets/propertyimage/K&K.jpg",
    webPage: "./properties/1440-S-Liberty.html",
    lat: 39.15625,
    lng: -86.57774,
  },
  {
    id: 12,
    name: "Ami",
    new: "",
    address: "1500 E. 3rd Street",
    city: "Bloomington",
    state: "IN",
    zip: "47401",
    info: "",
    imageUrl: "./assets/propertyimage/ami.jpg",
    webPage: "./properties/1500-E-3rd.html",
    lat: 39.16415,
    lng: -86.51510,
  },
  {
    id: 5,
    name: "Starbucks",
    new: "",
    address: "2105 Liberty Drive",
    city: "Bloomington",
    state: "IN",
    zip: "47403",
    info: "",
    imageUrl: "./assets/propertyimage/starbucks.jpg",
    webPage: "./properties/2105-Liberty.html",
    lat: 39.14598,
    lng: -86.57715,
  },
  {
    id: 1,
    name: "Lincoln Square Pancake House",
    new: "",
    address: "2160 N. Walnut Street",
    city: "Bloomington",
    state: "IN",
    zip: "47404",
    info: "",
    imageUrl: "./assets/propertyimage/lsph.jpg",
    webPage: "./properties/2160-N-Walnut.html",
    lat: 39.18600,
    lng: -86.53413,
  },
  {
    id: 19,
    name: "Hostetler Plumbing",
    new: "",
    address: "2282 W. Industrial Park Drive",
    city: "Bloomington",
    state: "IN",
    zip: "47404",
    info: "",
    imageUrl: "./assets/propertyimage/hostetler.jpg",
    webPage: "./properties/2282-Industrial.html",
    lat: 39.17511,
    lng: -86.56875,
  },
  {
    id: 56,
    name: "Kingdom Roofing",
    new: "",
    address: "2310 S. Hickory Drive",
    city: "Bloomington",
    state: "IN",
    zip: "47403",
    info: "",
    imageUrl: "./assets/propertyimage/hickory.jpg",
    webPage: "./properties/2310-S-Hickory.html",
    lat: 39.14465,
    lng: -86.57813,
  },
  {
    id: 23,
    name: "Gannett Co.",
    new: "",
    address: "2332 W. Industrial Park Drive",
    city: "Bloomington",
    state: "IN",
    zip: "47404",
    info: "",
    imageUrl: "./assets/propertyimage/heraldtimes.jpg",
    webPage: "./properties/2332-Industrial.html",
    lat: 39.17535,
    lng: -86.56809,
  },
  {
    id: 24,
    name: "Follet + Lute Supply",
    new: "",
    address: "2356 W. Industrial Park Drive",
    city: "Bloomington",
    state: "IN",
    zip: "47404",
    info: "",
    imageUrl: "./assets/propertyimage/follet.jpg",
    webPage: "./properties/2356-Industrial.html",
    lat: 39.17548,
    lng: -86.56772,
  },
  // {
  //   id: 29,
  //   name: "Therapy One",
  //   new: "",
  //   address: "2411 S. Curry Pike",
  //   city: "Bloomington",
  //   state: "IN",
  //   zip: "47403",
  //   info: "",
  //   imageUrl: "./assets/propertyimage/therapyone.jpg",
  //   webPage: "./properties/2411-S-Curry.html",
  //   lat: 39.1432,
  //   lng: -86.5823,
  // },
  {
    id: 3,
    name: "Travel Lobster",
    new: "",
    address: "2615-2621 E. 3rd Street",
    city: "Bloomington",
    state: "IN",
    zip: "47401",
    info: "",
    imageUrl: "./assets/propertyimage/redlobster.jpg",
    webPage: "./properties/travel-lobster.html",
    lat: 39.16469,
    lng: -86.4993,
  },
  {
    id: 30,
    name: "At Home",
    new: "",
    address: "3175 W. 3rd Street",
    city: "Bloomington",
    state: "IN",
    zip: "47404",
    info: "",
    imageUrl: "./assets/propertyview/athome.jpg",
    webPage: "./properties/3175-W-3rd.html",
    lat: 39.16271,
    lng: -86.57533,
  },
  {
    id: 25,
    name: "First Financial Bank",
    new: "",
    address: "3205 E. 3rd Street",
    city: "Bloomington",
    state: "IN",
    zip: "47401",
    info: "",
    imageUrl: "./assets/propertyimage/firstfinancial.jpg",
    webPage: "./properties/3205-E-3rd.html",
    lat: 39.16453,
    lng: -86.49275,
  },
  {
    id: 57,
    name: "Big Red Liquors",
    new: "",
    address: "3207 E. 3rd Street",
    city: "Bloomington",
    state: "IN",
    zip: "47403",
    info: "",
    imageUrl: "./assets/propertyimage/bigredliquors.jpg",
    webPage: "./properties/3207-E-3rd.html",
    lat: 39.16464,
    lng: -86.4925,
  },
  {
    id: 58,
    name: "Bedford Shoppes",
    new: "",
    address: "3302 John A Williams Blvd",
    city: "Bedford",
    state: "IN",
    zip: "47421",
    info: "",
    imageUrl: "./assets/propertyimage/1477_main.jpg",
    webPage: "./properties/1477-Main.html",
    lat: 38.86727,
    lng: -86.52124,
  },
  {
    id: 31,
    name: "Fresh Thyme Market",
    new: "",
    address: "3600 W. 3rd Street",
    city: "Bloomington",
    state: "IN",
    zip: "47404",
    info: "",
    imageUrl: "./assets/propertyimage/freshthyme.jpg",
    webPage: "./properties/3600-W-3rd.html",
    lat: 39.16597,
    lng: -86.57957,
  },
  {
    id: 13,
    name: "American Midwest",
    new: "",
    address: "4201 E. 3rd Street",
    city: "Bloomington",
    state: "IN",
    zip: "47401",
    info: "",
    imageUrl: "./assets/propertyimage/lamaoffice.jpg",
    webPage: "./properties/4201-E-3rd.html",
    lat: 39.16466,
    lng: -86.47817,
  },
  {
    id: 59,
    name: "Irvington Shoppes",
    new: "",
    address: "5614 East Washington Street",
    city: "Indianapolis",
    state: "IN",
    zip: "47421",
    info: "",
    imageUrl: "./assets/propertyimage/irvington.jpg",
    webPage: "./properties/5614-Washington.html",
    lat: 39.77115,
    lng: -86.07149,
  },
  {
    id: 45,
    name: "Parsons Xtreme Golf",
    new: "",
    address: "6091 E. 82nd Street",
    city: "Indianapolis",
    state: "IN",
    zip: "46250",
    info: "",
    imageUrl: "./assets/propertyimage/pxg.jpg",
    webPage: "./properties/6091-E-82nd.html",
    lat: 39.90480,
    lng: -86.0615,
  },
  {
    id: 48,
    name: "Phillips 66 - Indianapolis",
    new: "",
    address: "7751 S. Meridian",
    city: "Indianapolis",
    state: "IN",
    zip: "46217",
    info: "",
    imageUrl: "./assets/propertyimage/philips66-indy.jpg",
    webPage: "./properties/7751-S-Meridian.html",
    lat: 39.65373,
    lng: -86.15787,
  },
  {
    id: 47,
    name: "Village Pantry",
    new: "",
    address: "9550 Hague Road",
    city: "Indianapolis",
    state: "IN",
    zip: "46256",
    info: "",
    imageUrl: "./assets/propertyimage/villagepantry-indy.jpg",
    webPage: "./properties/9550-Hague.html",
    lat: 39.9266,
    lng: -86.0269,
  },
  {
    id: 50,
    name: "Circle K - Fishers",
    new: "",
    address: "9606 Olio Road",
    city: "Fishers",
    state: "IN",
    zip: "46055",
    info: "",
    imageUrl: "./assets/propertyimage/circlek-fishers.jpg",
    webPage: "./properties/9606-Olio.html",
    lat: 39.92844,
    lng: -85.91817,
  },
  {
    id: 46,
    name: "Nora Urgent Care",
    new: "",
    address: "10950 Pendleton Pike",
    city: "Indianapolis",
    state: "IN",
    zip: "46236",
    info: "",
    imageUrl: "./assets/propertyimage/noraurgentcare.jpeg",
    webPage: "./properties/10950-Pendleton.html",
    lat: 39.86284,
    lng: -85.97338,
  },
  {
    id: 49,
    name: "G5 Auto Sales",
    new: "",
    address: "11544 Allisonville Road",
    city: "Fishers",
    state: "IN",
    zip: "46038",
    info: "",
    imageUrl: "./assets/propertyimage/g5autosales.jpeg",
    webPage: "./properties/11544-Allisonville.html",
    lat: 39.95363,
    lng: -86.04181,
  },
  {
    id: 52,
    name: "Circle K - Noblesville",
    new: "",
    address: "14544 Herriman Boulevard",
    city: "Noblesville",
    state: "IN",
    zip: "46060",
    info: "",
    imageUrl: "./assets/propertyimage/circlek-noblesville.jpg",
    webPage: "./properties/14544-Herriman.html",
    lat: 40.00025,
    lng: -86.00485,
  },
];

// Initialize the map
const map = L.map("mapid").setView([39.4977, -86.2097], 9);

// Add the tile layer to the map
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
  attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
}).addTo(map);

// Initialize marker cluster
const markers = L.markerClusterGroup();

// Add markers to the map and populate the property list
properties.forEach((property) => {
  // Create a marker and add it to the marker cluster
  const marker = L.marker([property.lat, property.lng]);
  marker.propertyId = property.id;
  markers.addLayer(marker);

  // Create a popup for the marker
  const popupContent = `
    <img src="${property.imageUrl}" class="border border-dark border-2 border-solid rounded mx-auto d-block" alt="${property.name}" width="300" height="200" />
    <h4 class="p-0 mx-2 my-0">
      ${property.name}
      <img src="${property.new}" class="new" width="20" height="auto" />
    </h4>
    <p class="p-0 mx-2 my-0">${property.address}</p>
    <p class="p-0 mx-2 my-0">${property.city}, ${property.state} ${property.zip}</p>
    <p class="p-0 mx-2 my-2">${property.info}</p>
    <a href="${property.webPage}" class="btn btn-dark mx-1 my-0" style="color: #fff">Learn More</a>
    
    `;
  marker.bindPopup(popupContent);

  // Add property to the property list
  const propertyListItem = `
    <div class="property-item" id="property-${property.id}">
      <img src="${property.imageUrl}" class="border border-dark border-2 border-solid rounded mx-auto d-block" alt="${property.name}" width="300" height="200" />
      <h4 class="p-0 mx-4 my-0">
        ${property.name}
        <img src="${property.new}" class="new" width="20" height="auto" />
      </h4>
      <p class="p-0 mx-4 my-0">${property.address}</p>
      <p class="p-0 mx-4 mb-2">${property.city}, ${property.state} ${property.zip}</p>
      <p class="p-0 mx-4 mb-2">${property.info}</p>
    <div class="property-actions mx-auto">
      <a href="${property.webPage}" target="_blank" class="btn btn-dark my-0" style="color: #fff">Learn More</a>
      <button class="btn btn-dark center-on-map" data-lat="${property.lat}" data-lng="${property.lng}">Center on Map</button>
    </div>
    </div>
  `;
  document.getElementById("property-list").innerHTML += propertyListItem;
});

// Add marker cluster to the map
map.addLayer(markers);

// Marker click event to scroll and highlight the property in the list
markers.on("click", (e) => {
  const propertyId = e.layer.propertyId;
  const propertyElement = document.getElementById(`property-${propertyId}`);
  removeHighlightFromAllProperties();
  propertyElement.scrollIntoView({ behavior: "smooth", block: "center" });
  propertyElement.classList.add("highlighted");
});

// Marker click event to remove the highlight from the property in the list
function removeHighlightFromAllProperties() {
  const propertyItems = document.querySelectorAll(".property-item.highlighted");
  propertyItems.forEach((propertyItem) => {
    propertyItem.classList.remove("highlighted");
  });
}

// Center on map button click event
document.querySelectorAll(".center-on-map").forEach((button) => {
  button.addEventListener("click", (e) => {
    const lat = parseFloat(e.target.dataset.lat);
    const lng = parseFloat(e.target.dataset.lng);
    map.flyTo([lat, lng], 18);

    const propertyElement = e.target.closest(".property-item");
    removeHighlightFromAllProperties();
    propertyElement.classList.add("highlighted");

  });
});

