// Property data
const properties = [
  {
    id: 1,
    name: "Red Lobster",
    address: "2617 E. 3rd Street",
    city: "Bloomington",
    state: "IN",
    zip: "47401",
    info: "",
    imageUrl: "./propertyimage/redlobster.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16469,
    lng: -86.4993,
  },
  {
    id: 2,
    name: "Travelodge by Windham",
    address: "2615 E. 3rd Street",
    city: "Bloomington",
    state: "IN",
    zip: "47401",
    info: "",
    imageUrl: "./propertyimage/travelodge.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16466,
    lng: -86.4998,
  },
  {
    id: 3,
    name: "Jiffy Lube",
    address: "2621 E. 3rd Street",
    city: "Bloomington",
    state: "IN",
    zip: "47401",
    info: "",
    imageUrl: "./propertyimage/jiffylube.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16569,
    lng: -86.49977,
  },
  {
    id: 4,
    name: "Midas",
    address: "2619 E. 3rd Street",
    city: "Bloomington",
    state: "IN",
    zip: "47401",
    info: "",
    imageUrl: "./propertyimage/midas.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16611,
    lng: -86.49984,
  },
  {
    id: 5,
    name: "Starbucks",
    address: "2105 Liberty Drive",
    city: "Bloomington",
    state: "IN",
    zip: "47403",
    info: "Park 37, Lot 13",
    imageUrl: "./propertyimage/starbucks.jpg",
    webPage: "./properties/construction.html",
    lat: 39.14598,
    lng: -86.57715,
  },
  {
    id: 6,
    name: "Toppers",
    address: "212 S. Indiana Avenue",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./propertyimage/toppers.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16490,
    lng: -86.52706,
  },
  {
    id: 7,
    name: "Chow Bar",
    address: "212 S. Indiana Avenue",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./propertyimage/chowbar.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16478,
    lng: -86.52725,
  },
  {
    id: 8,
    name: "Burma Garden Restaurant",
    address: "413 E. 4th Street",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./propertyimage/burmagarden.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16572,
    lng: -86.52910,
  },
  {
    id: 9,
    name: "Korea Restaurant",
    address: "409 E. 4th Street",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./propertyimage/korearestaurant.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16575,
    lng: -86.52928,
  },
  {
    id: 10,
    name: "Anatolia",
    address: "409 E. 4th Street",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./propertyimage/anatolia.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16572,
    lng: -86.52910,
  },
  {
    id: 11,
    name: "India Garden",
    address: "416 E. 4th Street",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./propertyimage/indiagarden.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16545,
    lng: -86.52869,
  },
  {
    id: 12,
    name: "Ami",
    address: "1500 E. 3rd Street",
    city: "Bloomington",
    state: "IN",
    zip: "47401",
    info: "",
    imageUrl: "./propertyimage/ami.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16415,
    lng: -86.51510,
  },
  {
    id: 13,
    name: "Schultz Reagon, LLC",
    address: "4201 E. 3rd Street",
    city: "Bloomington",
    state: "IN",
    zip: "47401",
    info: "",
    imageUrl: "./propertyimage/mattschultz.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16466,
    lng: -86.47789,
  },
  {
    id: 14,
    name: "American Midwest",
    address: "4201 E. 3rd Street",
    city: "Bloomington",
    state: "IN",
    zip: "47401",
    info: "",
    imageUrl: "./propertyimage/americanmidwest.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16466,
    lng: -86.47789,
  },
  {
    id: 15,
    name: "Avanti Salon",
    address: "4201 E. 3rd Street",
    city: "Bloomington",
    state: "IN",
    zip: "47401",
    info: "",
    imageUrl: "./propertyimage/mattschultz.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16466,
    lng: -86.47789,
  },
  {
    id: 16,
    name: "Rajesh Station",
    address: "275 E. Winslow Road",
    city: "Bloomington",
    state: "IN",
    zip: "47401",
    info: "",
    imageUrl: "./propertyimage/rajeshstation.jpg",
    webPage: "./properties/construction.html",
    lat: 39.13643,
    lng: -86.52726,
  },
  {
    id: 17,
    name: "Grab n Go",
    address: "901 N. Indiana Avenue",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./propertyimage/grabngo.jpg",
    webPage: "./properties/construction.html",
    lat: 39.17478,
    lng: -86.52730,
  },
  {
    id: 18,
    name: "Village Pantry",
    address: "1320 E. 3rd Street",
    city: "Bloomington",
    state: "IN",
    zip: "47401",
    info: "",
    imageUrl: "./propertyimage/villagepantry.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16408,
    lng: -86.51669,
  },
  {
    id: 19,
    name: "NPAG",
    address: "2282 W. Industrial Park Drive",
    city: "Bloomington",
    state: "IN",
    zip: "47404",
    info: "",
    imageUrl: "./propertyimage/npag.jpg",
    webPage: "./properties/construction.html",
    lat: 39.17511,
    lng: -86.56875,
  },
  {
    id: 20,
    name: "Lincoln Square Pancake House",
    address: "2160 N. Walnut Street",
    city: "Bloomington",
    state: "IN",
    zip: "47404",
    info: "",
    imageUrl: "./propertyimage/lsph.png",
    webPage: "./properties/construction.html",
    lat: 39.18600,
    lng: -86.53413,
  },
  {
    id: 21,
    name: "Pizza Hut",
    address: "125 S. Franklin Road",
    city: "Bloomington",
    state: "IN",
    zip: "47404",
    info: "",
    imageUrl: "./propertyimage/pizzahut.png",
    webPage: "./properties/construction.html",
    lat: 39.16587,
    lng: -86.57067,
  },
  {
    id: 22,
    name: "Riviera Maya",
    address: "116 S. Franklin Road",
    city: "Bloomington",
    state: "IN",
    zip: "47404",
    info: "",
    imageUrl: "./propertyimage/rivieramaya.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16741,
    lng: -86.57157,
  },
  {
    id: 23,
    name: "Byers Scientific",
    address: "2332 W. Industrial Park Drive",
    city: "Bloomington",
    state: "IN",
    zip: "47404",
    info: "",
    imageUrl: "./propertyimage/rivieramaya.jpg",
    webPage: "./properties/construction.html",
    lat: 39.17535,
    lng: -86.56809,
  },
  {
    id: 24,
    name: "Follet",
    address: "2356 W. Industrial Park Drive",
    city: "Bloomington",
    state: "IN",
    zip: "47404",
    info: "",
    imageUrl: "./propertyimage/follet.jpg",
    webPage: "./properties/construction.html",
    lat: 39.17548,
    lng: -86.56772,
  },
  {
    id: 25,
    name: "First Financial Bank",
    address: "3205 E. 3rd Street",
    city: "Bloomington",
    state: "IN",
    zip: "47401",
    info: "",
    imageUrl: "./propertyimage/firstfinancial.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16453,
    lng: -86.49275,
  },
  {
    id: 26,
    name: "Smokin' Jack's Rib Shack",
    address: "505 W. 17th Street",
    city: "Bloomington",
    state: "IN",
    zip: "47404",
    info: "",
    imageUrl: "./propertyimage/smokinjacks.jpg",
    webPage: "./properties/construction.html",
    lat: 39.17872,
    lng: -86.53865,
  },
  {
    id: 27,
    name: "Performance Refinish Supply",
    address: "1400 W. Bloomfield Road",
    city: "Bloomington",
    state: "IN",
    zip: "47403",
    info: "",
    imageUrl: "./propertyimage/performancesupply.jpg",
    webPage: "./properties/construction.html",
    lat: 39.15956,
    lng: -86.55563,
  },
  {
    id: 28,
    name: "Sunset Hill Fence",
    address: "1440 W. Bloomfield Road",
    city: "Bloomington",
    state: "IN",
    zip: "47403",
    info: "",
    imageUrl: "./propertyimage/sunsethillfence.jpg",
    webPage: "./properties/construction.html",
    lat: 39.15291,
    lng: -86.56550,
  },
  {
    id: 29,
    name: "Medical One",
    address: "2411 S. Curry Pike",
    city: "Bloomington",
    state: "IN",
    zip: "47403",
    info: "",
    imageUrl: "./propertyimage/medicalone.jpg",
    webPage: "./properties/construction.html",
    lat: 39.14340,
    lng: -86.58222,
  },
  {
    id: 30,
    name: "At Home",
    address: "3175 W. 3rd Street",
    city: "Bloomington",
    state: "IN",
    zip: "47404",
    info: "",
    imageUrl: "./propertyimage/athome.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16271,
    lng: -86.57533,
  },
  {
    id: 31,
    name: "Fresh Thyme Market",
    address: "3600 W. 3rd Street",
    city: "Bloomington",
    state: "IN",
    zip: "47404",
    info: "",
    imageUrl: "./propertyimage/freshthyme.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16597,
    lng: -86.57957,
  },
  {
    id: 32,
    name: "Kroger",
    address: "155 S. Kingston Drive",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./propertyimage/kroger.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16612,
    lng: -86.49220,
  },
  {
    id: 33,
    name: "Yatagarasu Ramen",
    address: "430 E. Kirkwood Avenue",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./propertyimage/yatagarasu.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16628,
    lng: -86.52853,
  },
  {
    id: 34,
    name: "Jimmy John's",
    address: "430 E. Kirkwood Avenue",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./propertyimage/jimmyjohns.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16627,
    lng: -86.52848,
  },
  {
    id: 35,
    name: "The Upstairs Pub",
    address: "430 E. Kirkwood Avenue",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./propertyimage/jimmyjohns.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16644,
    lng: -86.52837,
  },
  {
    id: 36,
    name: "Chase ATM",
    address: "502 E. Kirkwood Avenue",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./propertyimage/chaseatm.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16643,
    lng: -86.52804,
  },
  {
    id: 37,
    name: "Z&C Teriyaki & Sushi",
    address: "430 E. Kirkwood Avenue",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./propertyimage/ZCTeriyaki.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16641,
    lng: -86.52859,
  },
  {
    id: 38,
    name: "Insomnia Cookies",
    address: "430 E. Kirkwood Avenue",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./propertyimage/insomniacookies.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16627,
    lng: -86.52848,
  },
  //Space and ID 39 reserved for Falafel's/Rita's; ask Eric
  {
    id: 40,
    name: "Crimson Nails & Spa",
    address: "161 S. Kingston Drive",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./propertyimage/crimsonnails.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16601,
    lng: -86.49118,
  },
  {
    id: 41,
    name: "World of Dance",
    address: "149 S. Kingston Drive",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./propertyimage/worldofdance.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16612,
    lng: -86.49114,
  },
  {
    id: 42,
    name: "DaVita Hoosier Hills Dialysis",
    address: "143 S. Kingston Drive",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./propertyimage/davita.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16603,
    lng: -86.49105,
  },
  {
    id: 43,
    name: "Dr. William E. Arnold Jr.",
    address: "167 S. Kingston Drive",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    info: "",
    imageUrl: "./propertyimage/williamarnold.jpg",
    webPage: "./properties/construction.html",
    lat: 39.16583,
    lng: -86.49114,
  },
  //Kingston Shoppes Vacant Slot; reserve id 44
  {
    id: 45,
    name: "PXG",
    address: "6091 E. 82nd Street",
    city: "Indianapolis",
    state: "IN",
    zip: "46250",
    info: "",
    imageUrl: "./propertyimage/pxg.jpg",
    webPage: "./properties/construction.html",
    lat: 39.90534,
    lng: -86.06668,
  },
  {
    id: 46,
    name: "Nora Urgent Care",
    address: "10950 Pendleton Pike",
    city: "Indianapolis",
    state: "IN",
    zip: "46236",
    info: "",
    imageUrl: "./propertyimage/nora.jpg",
    webPage: "./properties/construction.html",
    lat: 39.86284,
    lng: -85.97338,
  },
  {
    id: 47,
    name: "Marathon",
    address: "9550 Hague Road",
    city: "Indianapolis",
    state: "IN",
    zip: "46256",
    info: "",
    imageUrl: "./propertyimage/marathon.jpg",
    webPage: "./properties/construction.html",
    lat: 39.92688,
    lng: -86.02682,
  },
  {
    id: 48,
    name: "Phillips 66 - Indianapolis",
    address: "7751 S. Meridian",
    city: "Indianapolis",
    state: "IN",
    zip: "46217",
    info: "",
    imageUrl: "./propertyimage/phillips66.jpg",
    webPage: "./properties/construction.html",
    lat: 39.65373,
    lng: -86.15787,
  },
  {
    id: 49,
    name: "G5 Auto Sales",
    address: "11544 Allisonville Road",
    city: "Fishers",
    state: "IN",
    zip: "46038",
    info: "",
    imageUrl: "./propertyimage/g5autosales.jpg",
    webPage: "./properties/construction.html",
    lat: 39.95363,
    lng: -86.04181,
  },
  {
    id: 50,
    name: "Circle K - Fishers",
    address: "9609 Olio Road",
    city: "Fishers",
    state: "IN",
    zip: "46055",
    info: "",
    imageUrl: "./propertyimage/circlek.jpg",
    webPage: "./properties/construction.html",
    lat: 39.92844,
    lng: -85.91817,
  },
  //id 51 reserved for first merchants bank; ask eric
  {
    id: 52,
    name: "Circle K - Noblesville",
    address: "14554 Herriman Boulevard",
    city: "Noblesville",
    state: "IN",
    zip: "46060",
    info: "",
    imageUrl: "./propertyimage/circlek.jpg",
    webPage: "./properties/construction.html",
    lat: 40.00015,
    lng: -86.00485,
  },
  {
    id: 53,
    name: "Circle K - Carmel",
    address: "14554 Herriman Boulevard",
    city: "Carmel",
    state: "IN",
    zip: "46060",
    info: "",
    imageUrl: "./propertyimage/circlek.jpg",
    webPage: "./properties/construction.html",
    lat: 39.97339,
    lng: -86.12659,
  },
  {
    id: 54,
    name: "Phillips 66 - Columbus",
    address: "910 3rd Street",
    city: "Columbus",
    state: "IN",
    zip: "47201",
    info: "",
    imageUrl: "./propertyimage/phillips.jpg",
    webPage: "./properties/construction.html",
    lat: 39.20190,
    lng: -85.91406,
  },
];

// Initialize the map
const map = L.map("mapid").setView([39.4977, -86.2097], 9);

// Add the tile layer to the map
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
  attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
}).addTo(map);

// Initialize marker cluster
const markers = L.markerClusterGroup();

// Add markers to the map and populate the property list
properties.forEach((property) => {
  // Create a marker and add it to the marker cluster
  const marker = L.marker([property.lat, property.lng]);
  marker.propertyId = property.id;
  markers.addLayer(marker);

  // Create a popup for the marker
  const popupContent = `
    <img src="${property.imageUrl}" class="border border-dark border-2 border-solid rounded mx-auto d-block" alt="${property.name}" width="300" height="200" />
    <h3 class="p-0 mx-2 my-0">${property.name}</h3>
    <p class="p-0 mx-2 my-0">${property.address}</p>
    <p class="p-0 mx-2 my-0">${property.city}, ${property.state} ${property.zip}</p>
    <p class="p-0 mx-2 my-2">${property.info}</p>
    <a href="${property.webPage}" class="btn btn-dark mx-1 my-0" style="color: #fff">Learn More</a>
  `;
  marker.bindPopup(popupContent);

  // Add property to the property list
  const propertyListItem = `
    <div class="property-item" id="property-${property.id}">
      <img src="${property.imageUrl}" class="border border-dark border-2 border-solid rounded mx-auto d-block" alt="${property.name}" width="300" height="200" />
      <h4 class="p-0 mx-4 my-0">${property.name}</h4>
      <p class="p-0 mx-4 my-0">${property.address}</p>
      <p class="p-0 mx-4 mb-2">${property.city}, ${property.state} ${property.zip}</p>
      <p class="p-0 mx-4 mb-2">${property.info}</p>
    <div class="property-actions mx-auto">
      <a href="${property.webPage}" target="_blank" class="btn btn-dark my-0" style="color: #fff">Learn More</a>
      <button class="btn btn-dark center-on-map" data-lat="${property.lat}" data-lng="${property.lng}">Center on Map</button>
    </div>
    </div>
  `;
  document.getElementById("property-list").innerHTML += propertyListItem;
});

// Add marker cluster to the map
map.addLayer(markers);

// Marker click event to scroll and highlight the property in the list
markers.on("click", (e) => {
  const propertyId = e.layer.propertyId;
  const propertyElement = document.getElementById(`property-${propertyId}`);
  removeHighlightFromAllProperties();
  propertyElement.scrollIntoView({ behavior: "smooth", block: "center" });
  propertyElement.classList.add("highlighted");
});

// Marker click event to remove the highlight from the property in the list
function removeHighlightFromAllProperties() {
  const propertyItems = document.querySelectorAll(".property-item.highlighted");
  propertyItems.forEach((propertyItem) => {
    propertyItem.classList.remove("highlighted");
  });
}

// Center on map button click event
document.querySelectorAll(".center-on-map").forEach((button) => {
  button.addEventListener("click", (e) => {
    const lat = parseFloat(e.target.dataset.lat);
    const lng = parseFloat(e.target.dataset.lng);
    map.flyTo([lat, lng], 18);

    const propertyElement = e.target.closest(".property-item");
    removeHighlightFromAllProperties();
    propertyElement.classList.add("highlighted");

  });
});

